lib/ethduel/web/router.ex
defmodule Ethduel.Web.Router do
  use Ethduel.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    #plug :Ethduel.Metamask, repo: Ethduel.Repo
    #plug :put_wallet_token
  end


  scope "/", Ethduel.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/name", NameController, only: [:create]
    get "/game/random", GameController, :random
    get "/game/:gameid", GameController, :view
    get "/account", AccountController, :index
    get "/account/:walletAddress", AccountController, :view
    get "/help", HelpController, :index
  end

end

lib/ethduel/web/controllers/account_controller.ex
defmodule Ethduel.Web.AccountController do
  use Ethduel.Web, :controller
  require Logger

  def index(conn, _params) do
    render(conn, "account.html")
  end

   def view(conn, %{"walletAddress" => walletAddress}) do
    render(conn, "account.html", walletAddress: walletAddress)
  end
end

lib/ethduel/web/controllers/game_controller.ex
defmodule Ethduel.Web.GameController do
  use Ethduel.Web, :controller
  require Logger
  require ConCache
  alias Ethduel.{RiotUtil, Repo, Game}
  import Ecto.Query

  def index(conn, _params) do
    conn |> put_flash(:error, "Redirecting to homepage") |> redirect(to: "/") |> halt()
  end
  
  # check the database for teams, then check cache for updated time info.
  def view(conn, %{"gameid" => gameid}) do

    #get teams from Ecto
    query = from p in Game, 
            where: p.riot_game_id == ^gameid, 
            select: p.champions
    teams = List.first(Repo.all(query))

    #if that query fails due to DB load could fallback to teams = RiotUtil.getCachedTeamsFromID(gameid).  Don't know if its worth keeping that cache around

    #get the true game time
    {gameLength, trueGameLength} = RiotUtil.getTrueGameLength(gameid)
    if gameLength == 0, do: gameTime = -999, else: gameTime = trueGameLength
    
    render(conn, "leaguegame.html", gameid: gameid, teams: teams, gameTime: gameTime)
  end

  def random(conn, _param) do
    with {:ok, gameId} <- RiotUtil.getRandomRecentGame() do
      redirect conn, to: "/game/#{gameId}"
    else
      {:error, reason} -> 
        conn 
        |> put_flash(:error, "No recent games found. Try searching for a player!") 
        |> redirect(to: "/")
      end
  end
end


    
    

lib/ethduel/web/controllers/help_controller.ex
defmodule Ethduel.Web.HelpController do
  use Ethduel.Web, :controller
  require Logger

  def index(conn, _params) do
    render(conn, "help.html")
  end
end

lib/ethduel/web/controllers/name_controller.ex
defmodule Ethduel.Web.NameController do
  use Ethduel.Web, :controller
  require Logger
  require ConCache
  alias Ethduel.{RiotUtil, Game}

  def index(conn, _params) do
    conn |> put_flash(:error, "Redirecting to homepage") |> redirect(to: "/") |> halt()
  end

  def create(conn, _params) do
    region = conn.params["parameters"]["region"]
    name = conn.params["parameters"]["name"]
    gameId = RiotUtil.checkNameInCache(region, name)
    if gameId do 
      IO.puts("#{name} in cache, redirecting without API call")
      redirect conn, to: "/game/#{gameId}"
    else 
      with {:ok, gameInfo} <- RiotUtil.getGameFromName(region, name) do
        gameId = RiotUtil.getGameIdFromGame(gameInfo)
        Game.insertGame(gameId, gameInfo, region)
        RiotUtil.putDataInConCache(region, gameInfo)
        redirect conn, to: "/game/#{gameId}"
      else 
        {:error, _} ->
          conn
          |> put_flash(:error, "#{name} not found in a #{region} region game.") 
          |> redirect(to: "/")
      end
    end
  end
end

lib/ethduel/web/controllers/page_controller.ex
defmodule Ethduel.Web.PageController do
  use Ethduel.Web, :controller
  alias Ethduel.RiotUtil

  def index(conn, _params) do
    #recentgames = RiotUtil.getRecentGamesList()
    populargames = [["4", "24", "23", "11", "12", "15", "27", "28", "33", "36"], ["40", "41", "23", "42", "43", "45", "28", "48", "50", "51"], ["53", "54", "55", "56", "57", "58", "59", "60", "61", "62"], ["63", "64", "67", "81", "80", "82", "83", "84", "85", "86"], ["89", "90", "91", "92", "96", "101", "102", "103", "104", "105"]]
    render(conn, "index.html", populargames: populargames)
  end

  def view(conn, _params) do
    render(conn, "index.html")
  end

end

lib/ethduel/web/views/account_view.ex
defmodule Ethduel.Web.AccountView do
  use Ethduel.Web, :view

  def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end
  
end

lib/ethduel/web/views/chat_view.ex
defmodule Ethduel.ChatView do
  use Ethduel.Web, :view

  def render("chat.json", %{chat: chat}) do
    %{
      id: chat.id,
      body: chat.body,
      nickname: chat.nickname
    }
  end
end

lib/ethduel/web/views/error_view.ex
defmodule Ethduel.Web.ErrorView do
  use Ethduel.Web, :view

  def render("404.html", _assigns) do
     render("404_page.html", %{})
  end

  def render("500.html", _assigns) do
     render("500_page.html", %{})  
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500_page.html", assigns
  end
end

lib/ethduel/web/views/game_view.ex
defmodule Ethduel.Web.GameView do
  use Ethduel.Web, :view
  alias Ethduel.Chat


  def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end

  def connection_keys(conn) do
    conn
    |> Map.from_struct()
    |> Map.keys()
  end

end

lib/ethduel/web/views/help_view.ex
defmodule Ethduel.Web.HelpView do
  use Ethduel.Web, :view

  def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end
  
end

lib/ethduel/web/views/layout_view.ex
defmodule Ethduel.Web.LayoutView do
  use Ethduel.Web, :view
end

lib/ethduel/web/views/name_view.ex
defmodule Ethduel.Web.NameView do
  use Ethduel.Web, :view
  alias Chemist

  def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end

  def connection_keys(conn) do
    conn
    |> Map.from_struct()
    |> Map.keys()
  end
end

lib/ethduel/web/views/page_view.ex
defmodule Ethduel.Web.PageView do
  use Ethduel.Web, :view

  def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end

end

lib/ethduel/web/templates/game/betblue.html.eex
<div class="bet-blue">
  <button id="blue-bet-button">Place Bet on Blue</button>
</div>

lib/ethduel/web/templates/game/betred.html.eex
<div class="bet-red">
  <button id="red-bet-button">Place Bet on Red</button>
  </div>

lib/ethduel/web/templates/game/blueteam.html.eex
<div class="blue-team"></div>
    <%= for [champion, name] <- Enum.slice(@teams, 0, 5)  do %>
        <%= render(Ethduel.Web.GameView, "champion.html", conn: @conn, champion: champion, name: name) %>
    <% end %>   

lib/ethduel/web/templates/game/champion.html.eex
<div class="hover13">
    <figure class="champion">
    <var <%= namenospaces = String.replace(@name, " ", "%20") %></var>
    <a href= <%="http://lolprofile.net/summoner/na/" <> namenospaces %> target="_blank"> <img src="<%= static_path(@conn, "/images/champions/" <> @champion <> ".png") %>"></a>
    <figcaption class="caption">
    <%= @name %>
    </figcaption>
    </figure>
</div>

lib/ethduel/web/templates/game/chat.html.eex
<div id="msg-container" class="panel panel-default chat-room">
  <div id="chat-messages" class="panel-body panel-messages">
  </div>
    <input type="text" id="message-input" class="form-control" placeholder='Type a message...' maxlength="135"> 
</div> 
         

lib/ethduel/web/templates/game/gameinfo.html.eex
<div class="game-info">
  <div id="game-time-now"> <%= @gameTime %></div>
</div>

lib/ethduel/web/templates/game/leaguegame.html.eex
  <body class="leaguegame" id="league-game-body">
    <header class="leaguegame-header"><%= render Ethduel.Web.LayoutView, "header.html", conn: @conn %></header>
    <page class="league-content">

      <div class="blueteam"><%= render Ethduel.Web.GameView, "blueteam.html", conn: @conn, teams: @teams %></div>

      
      <div class="center-panels">
        <div id="bet-blue" class="bet-panel"><%= render Ethduel.Web.GameView, "betblue.html", conn: @conn %></div>
        <div id="game-info" class="other-panel"><%= render Ethduel.Web.GameView, "gameinfo.html", conn: @conn, gameTime: @gameTime %></div>
        <div id="bet-red" class="bet-panel"><%= render Ethduel.Web.GameView, "betred.html", conn: @conn %></div>
        <div id="chat-box" class="chat-panel other-panel"><%= render Ethduel.Web.GameView, "chat.html", conn: @conn %></div>
      </div>

      <div class="redteam"><%= render Ethduel.Web.GameView, "redteam.html", conn: @conn,  teams: @teams  %></div>
      </page>

    <footer <%= render Ethduel.Web.LayoutView, "footer.html", conn: @conn %></footer>
  </body>

lib/ethduel/web/templates/game/redteam.html.eex
<div class="red-team"></div>
    <%= for [champion, name] <- Enum.slice(@teams, 5, 5)  do %>
        <%= render(Ethduel.Web.GameView, "champion.html", conn: @conn, champion: champion, name: name) %>
    <% end %>

lib/ethduel/web/templates/help/faq.html.eex
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
         What is League of Legends? Ethereum? MetaMask? 
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <b>League of Legends</b> is an online 5 versus 5 battle arena, boasting over 100 million monthly active players all over the world, with games lasting around 30-45 minutes. <b>Ethereum</b> is a decentralized computing platform running a blockchain, similar to Bitcoin but with improvements.  Put simply, for Ethduel's purposes we are using it as a way to connect players from all around the world, and giving them an easy way to bet using the tokens of Ethereum, called Ether.  <b>MetaMask</b> is a trusted Chrome extension that connects your browser to the Ethereum network, and includes a secure identity vault, providing a user interface to manage your Ether wallet and sign blockchain transactions.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          What are the betting odds?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        Ethduel is a matching service for peers, so a bet pays out double minus 1% fee. League of Legends ranked matches attempt to place a player at the correct league for their skill level, so the expected win chance for any player or team is ~50%.  Ethduel does not engage in any betting, it only matches players or spectators with opposing bets.  Therefore, your bet is either lost or doubled, minus a 1% fee for Ethduel. 
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          How does betting work, in detail?
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        A user enters a betting lobby by searching for a player either in a game or in the game loading screen. A bet is initiated by clicking "Bet on Blue" or "Bet on Red", and enters into a first come, first served pool.  Ethduel will attempt to match it with the first opposing bet within a short time frame.  Unmatched bets can be cancelled, but once a bet is matched it is finalized.  The only way a matched bet can be cancelled is if the game is remade.  When a game ends, an automated program will send the winners their Ether within minutes, which can either be bet again or withdrawn back to MetaMask or another address of their choosing.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          How is the Ether on deposit stored?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
      There are multiple layers of security for the deposited Ether.  Ethduel servers run on DigitalOcean with 2FA account authentication, and have modern, secure firewall and access rules.  One of those servers is running the Parity Ethereum client, and deposited Ether is stored in an account there to be programmatically, <b>and only programmatically</b> accessed for user-initiated withdrawals. <em>AND YET</em>. Hacks and exit scams do happen, and until further Ethereum development happens Ethduel will not be fully decentralized and immune to those threats. Please do not store large amounts of Ether on Ethduel servers, as the funds can not be guaranteed nor insured. Ethduel will be issuing Bug Bounties, with prizes of lifetime fee-less betting and Ether.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          What about a player throwing the game on purpose?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <div class="panel-body">
        This is a tricky problem with a few imperfect solutions that will be added to the site quickly.  For now, Ethduel is starting out with only small bets allowed and we encourage you to use the game lobby or Discord chat to find bettors to match with. The in-game All Chat can be a tool to verify that a player is on a certain team.  Additionally, clicking on a player's portrait in the game lobby will take you to their <b>lolprofile.net</b> page. A feature coming soon is automated "code words" to be exchanged via All Chat that can verify a Blue player bet on Blue, and vice versa for Red.  
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          What is the development road map?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <div class="panel-body">
        Ethduel is intended to be a platform for worldwide, anonymous competition among players and spectators.  Right now it is reliant on game API's for bet resolution, so after polishing more features for League of Legends betting, new games like Dota 2 and Counterstrike: Global Offensive could be easily added. As the Ethereum network fees go down over time, it is the intent to move to a fully decentralized model with each game match having its own smart contract.    
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSeven">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
        Is this legal in my jurisdiction? Are you following regulatory compliance?
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
      <div class="panel-body">
      Ethduel allows users to participate in skill-based bets using cryptocurrency tokens, and is fully committed to complying with all regulatory and legal rules governing both e-sports and cryptocurrency. All users must attest to being over 18 years of age and agree not to use Ethduel to break any laws in their jurisdiction.
      </div>
    </div>
  </div>
   <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEight">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          Your question not here?
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
      <div class="panel-body">
        Please join us on Discord by clicking the link below, where the Ethduel team will answer any questions you have.
      </div>
    </div>
  </div>
</div>

lib/ethduel/web/templates/help/help.html.eex
<body>
<div><%= render Ethduel.Web.LayoutView, "header.html", conn: @conn%></div>

<div class="titles">
  <h2>Steps to Bet</h2>
  <h2>Steps to Deposit Ether</h2>
</div>

<div class=steps>
  <ol class="simple-list">
    <li>Search for the name of a player <b>in a game</b> or in the <b>loading screen</b> of a game in the search box above.</li>
    <li>With Ether deposited in your Ethduel account, click Bet on either the Blue or Red team. Ethduel will attempt to <b>match you</b> with a bettor for the other team.  If none is found in a short amount of time, the bet is fully refunded.</li>
    <li>To find opponents, users are encouraged to share their game link, such as <em><b>"ethduel.com/game/2599449128"</b></em> on sites like Twitch.</li>
    <li>At the end of the game, Ethduel will decide the winner based on the Riot API outcome of the match, and payout <b>double the bet</b> minus a 1% fee.</li>
  </ol>

  <ol class="simple-list">
    <li>The Ethereum network is similar to the Bitcoin network, and we need to a trusted way to connect to it.  Install the MetaMask browser extension, which is currently only available for Chrome (Firefox support coming soon), and can be found <a href="https://metamask.io" target="_blank">here</a>.</li>
    <li>Create a MetaMask password. <em><b>Do not forget this password!</b></em> It is the only way to access your funds in MetaMask and, through that, your funds in Ethduel. Save the recovery phrase, as that is the <b>only</b> way to recover your password.</li>
    <li>Buy or transfer Ether to your MetaMask wallet.  This can be done through MetaMask, or through any exchange such as Coinbase, Kraken, Gemini, etc.  A small amount can be bought through MetaMask with no registration, but you will need to go through the registration compliance on an exchange to purchase greater amounts. This can take <b>days or even a week</b> so start now!</li>
    <li>Finally, deposit Ether using the Ethduel UI.  It will show up within minutes and you are now ready to bet! Good luck!</li>
  </ol>
</div>

  <center>
  <div><h3>Common Questions</h3></div>
  <div><%= render Ethduel.Web.HelpView, "faq.html", conn: @conn  %></div>
  </center>

  <footer <%= render Ethduel.Web.LayoutView, "footer.html", conn: @conn %></footer>
</body>

lib/ethduel/web/templates/layout/aboutmodal.html.eex
<!-- Button trigger modal -->
<button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#aboutModal">
  About Ethduel
</button>

<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="aboutModalLabel">About</h4>
      </div>
      <div class="modal-body">
        <p>Ethduel is made possible by using Elixir and Phoenix for the backend and website, and MetaMask, Parity, and Ethereum for the Ether storage and transfer. </p>
        <p>Inquiries or messages for the Ethduel team should be made on Discord for now. </p> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

lib/ethduel/web/templates/layout/accountfunctions.html.eex
<%= render Ethduel.Web.LayoutView, "deposit.html", conn: @conn  %>
<%= render Ethduel.Web.LayoutView, "withdraw.html", conn: @conn  %>

lib/ethduel/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ethduel</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/ethduel/web/templates/layout/deposit.html.eex
<!-- Button trigger modal -->
<button type="button" id="deposit-button" disabled class="btn btn-info btn-sm" data-toggle="modal" data-target="#depositModal">
  Deposit
</button>

<!-- Modal -->
<div class="modal fade" id="depositModal" tabindex="-1" role="dialog" aria-labelledby="depositModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="depositModalLabel">Deposit Ether for Betting</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
            <label for="deposit-amount-input">Amount of Ether</label>
              <input class="form-control" id="deposit-amount-input" type="number" required placeholder="0.3" min="0" step="0.0000001" >
          </div>  
          <ul> Upon clicking Deposit a MetaMask confirmation prompt will appear, click Submit to complete the deposit. </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary pull-left" data-dismiss="modal">Cancel</button>
        <button type="submit" id="deposit-button-submit" class="btn btn-info" data-dismiss="modal">Deposit</button>
      </div>
    </div>
  </div>
</div>

lib/ethduel/web/templates/layout/discordbutton.html.eex
<a href="https://discord.gg/mmC4KXf" target="_blank"><button type="button" class="btn btn-info btn-xs">
  Join us on Discord
</button></a>

lib/ethduel/web/templates/layout/fate.html.eex
<div class=fate>
  <div class="hover13">
    <a href="<%= game_path(@conn, :random)%>"
    <figure class="champion">
     <img src="<%= static_path(@conn, "/images/fate.jpg") %>">
    </figure> </a>
  </div>
</div>

lib/ethduel/web/templates/layout/footer.html.eex
<div class="siteFooter">
  <!-- This section gets pushed to the left side-->
  <div class="siteHeader__section">
    <div id=header_logo><a href="https://discord.gg/mmC4KXf" target="_blank"><%= PhoenixInlineSvg.Helpers.svg_image(@conn, "discordicon") %></a> </div>
    <div class="siteFooter__item siteFooterButton"><%= render Ethduel.Web.LayoutView, "discordbutton.html", conn: @conn  %></div>
  </div>

  <!-- middle fate icon> -->
  <div class="siteFooter__section">
      <%= render Ethduel.Web.LayoutView, "fate.html", conn: @conn  %>
  </div>

  <!-- This section gets pushed to the right side-->
  <div class="siteFooter__section">
    <div class="siteFooter__item siteFooterButton"><%= render Ethduel.Web.LayoutView, "legalmodal.html", conn: @conn  %></div>
    <div class="siteFooter__item siteFooterButton"><%= render Ethduel.Web.LayoutView, "aboutmodal.html", conn: @conn  %></div>
  </div>
</div>

lib/ethduel/web/templates/layout/homepagefooter.html.eex
<div class="siteFooter">
  <!-- This section gets pushed to the left side-->
  <div class="siteHeader__section">
    <div id=header_logo><a href="https://discord.gg/mmC4KXf" target="_blank"><%= PhoenixInlineSvg.Helpers.svg_image(@conn, "discordicon") %></a> </div>
    <div class="siteFooter__item siteFooterButton"><%= render Ethduel.Web.LayoutView, "discordbutton.html", conn: @conn  %></div>
  </div>
  <!-- This section gets pushed to the right side-->
  <div class="siteFooter__section">
    <div class="siteFooter__item siteFooterButton"><%= render Ethduel.Web.LayoutView, "legalmodal.html", conn: @conn  %></div>
    <div class="siteFooter__item siteFooterButton"><%= render Ethduel.Web.LayoutView, "aboutmodal.html", conn: @conn  %></div>
  </div>
</div>

lib/ethduel/web/templates/layout/metamasktext.html.eex
<div class="metamasktext" id="metamask-text" style="text-align:center">
  <div class="spinner">
    <div class="bounce1"></div>
    <div class="bounce2"></div>
    <div class="bounce3"></div>
  </div>
</div>

lib/ethduel/web/templates/layout/searchbar.html.eex
<%= form_for @conn, name_path(@conn, :create), [as: :parameters], fn f -> %>
  <%= select f, :region, ["NA": "na1", "KR": "kr", "JP": "jp1", "OC": "oc1", "EUN": "eun1", "EUW": "euw1", "RU": "ru", "BR": "br1", "TR": "tr1", "LA1": "la1", "LA2": "la2", "PBE": "pbe1"] %>
  <%= text_input f, :name, placeholder: "Player Name" %>
  <%= submit "Find Game" %>
<% end %>

lib/ethduel/web/templates/layout/userbalance.html.eex
<div id="eth-user-balance"></div>
<div id="usd-user-balance"></div>
<div id="wei-user-balance" hidden></div>

lib/ethduel/web/templates/page/gamefacts.html.eex
<p>
15 bets
</br>
Time: 3:17
</br>
Diamond League 
</p>

lib/ethduel/web/templates/page/random.html.eex
 <!-- join a random recent game -->
 <div class="random"> 
    <div>Pick a card to quickly join a random, recent game lobby</div>
    
    <div class="hover13">
    <a href="<%= game_path(@conn, :random)%>"
    <figure class="card">
     <img src="<%= static_path(@conn, "/images/cards/bluecard.png") %>">
    </figure> </a>
  </div>
  <div class="hover13">
    <a href="<%= game_path(@conn, :random)%>"
    <figure class="card">
     <img src="<%= static_path(@conn, "/images/cards/redcard.png") %>">
    </figure> </a>
  </div>
   <div class="hover13">
    <a href="<%= game_path(@conn, :random)%>"
    <figure class="card">
     <img src="<%= static_path(@conn, "/images/cards/goldcard.png") %>">
    </figure> </a>
  </div>
  <div> <em>"It ain't luck, it's <b>destiny<b>"</em></div>
</div>